// mobile/src/components/player-card-visual.tsx
import { Image } from 'expo-image';
import { StyleSheet, Text, View } from 'react-native';

import { resolveApiResourceUrl } from '@/services/api';
import type { CardVisualTheme, PlayerAssets } from '@/features/players/types';

interface VisualPlayer {
  playerKor: string;
  ovr: number;
  position: string;
  nation?: string | null;
  team?: string | null;
  league?: string | null;
  pimage?: string | null;
  bimage?: string | null;
  assets?: PlayerAssets;
  cardTheme?: CardVisualTheme;
}

interface PlayerCardVisualProps {
  player: VisualPlayer;
  size: number;
}

const fallbackTheme: CardVisualTheme = {
  name: '#FFFFFF',
  ovr: '#FFFFFF',
  position: '#FFFFFF',
};

export function PlayerCardVisual({ player, size }: PlayerCardVisualProps) {
  const theme = player.cardTheme ?? fallbackTheme;
  const iconSize = size / 12;

  return (
    <View style={{ height: size, position: 'relative', width: size }}>
      {player.bimage && (
        <Image
          cachePolicy="memory-disk"
          contentFit="contain"
          source={{ uri: resolveApiResourceUrl(player.bimage) }}
          style={StyleSheet.absoluteFill}
          transition={150}
        />
      )}
      {player.pimage && (
        <Image
          accessibilityLabel={`${player.playerKor} 선수 이미지`}
          cachePolicy="memory-disk"
          contentFit="contain"
          source={{ uri: resolveApiResourceUrl(player.pimage) }}
          style={{ height: size * 0.93, left: size * 0.035, position: 'absolute', top: size * 0.035, width: size * 0.93 }}
          transition={150}
        />
      )}

      <Text
        style={[styles.overlayText, styles.ovr, {
          color: theme.ovr,
          fontSize: size * 0.125,
          left: size * 0.22,
          top: size * 0.1,
        }]}>
        {player.ovr}
      </Text>
      <Text
        style={[styles.overlayText, styles.position, {
          color: theme.position,
          fontSize: size * 0.084,
          left: size * 0.23,
          top: size * 0.24,
        }]}>
        {player.position}
      </Text>
      <Text
        numberOfLines={1}
        style={[styles.overlayText, styles.name, {
          bottom: size * 0.255,
          color: theme.name,
          fontSize: size * 0.0875,
          left: size * 0.225,
          width: size * 0.55,
        }]}>
        {player.playerKor}
      </Text>

      <View style={[styles.icons, { bottom: size * 0.161, gap: size * 0.05 }]}>
        {player.assets?.flag && (
          <Image
            accessibilityLabel={player.nation ?? '국가'}
            cachePolicy="memory-disk"
            contentFit="contain"
            source={{ uri: resolveApiResourceUrl(player.assets.flag) }}
            style={{ height: iconSize, width: iconSize }}
          />
        )}
        {player.assets?.league && (
          <Image
            accessibilityLabel={player.league ?? '리그'}
            cachePolicy="memory-disk"
            contentFit="contain"
            source={{ uri: resolveApiResourceUrl(player.assets.league) }}
            style={{ height: iconSize, width: iconSize }}
          />
        )}
        {player.assets?.team && (
          <Image
            accessibilityLabel={player.team ?? '팀'}
            cachePolicy="memory-disk"
            contentFit="contain"
            source={{ uri: resolveApiResourceUrl(player.assets.team) }}
            style={{ height: iconSize, width: iconSize }}
          />
        )}
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  icons: { alignItems: 'center', flexDirection: 'row', justifyContent: 'center', left: 0, position: 'absolute', right: 0 },
  name: { fontFamily: 'FCOAllSans-Regular', textAlign: 'center' },
  overlayText: { lineHeight: undefined, position: 'absolute' },
  ovr: { fontFamily: 'FCOAllSans-Bold' },
  position: { fontFamily: 'FCOAllSans-Regular' },
});

// src/components/PlayerCardVisual.vue
<script setup>
import { computed } from "vue";

const props = defineProps({
  player: { type: Object, required: true },
});

const themeStyle = computed(() => ({
  "--card-ovr-color": props.player.cardTheme?.ovr || "#ffffff",
  "--card-position-color": props.player.cardTheme?.position || "#ffffff",
  "--card-name-color": props.player.cardTheme?.name || "#ffffff",
}));

const hideMissingImage = (event) => {
  event.currentTarget.hidden = true;
};
</script>

<template>
  <div class="player-card-visual" :style="themeStyle">
    <img
      v-if="player.bimage"
      class="background"
      :src="player.bimage"
      alt=""
      @error="hideMissingImage"
    />
    <img
      v-if="player.pimage"
      class="render"
      :src="player.pimage"
      :alt="`${player.playerKor} 선수 이미지`"
      @error="hideMissingImage"
    />

    <strong class="ovr">{{ player.ovr }}</strong>
    <span class="position">{{ player.position }}</span>
    <span class="name">{{ player.playerKor }}</span>

    <span class="icons">
      <img
        v-if="player.assets?.flag"
        :src="player.assets.flag"
        :alt="player.nation || '국가'"
        @error="hideMissingImage"
      />
      <img
        v-if="player.assets?.league"
        :src="player.assets.league"
        :alt="player.league || '리그'"
        @error="hideMissingImage"
      />
      <img
        v-if="player.assets?.team"
        :src="player.assets.team"
        :alt="player.team || '팀'"
        @error="hideMissingImage"
      />
    </span>
  </div>
</template>

<style scoped>
.player-card-visual {
  aspect-ratio: 1;
  color: white;
  container-type: inline-size;
  isolation: isolate;
  position: relative;
  width: 100%;
}

.background,
.render {
  height: 100%;
  left: 50%;
  object-fit: contain;
  pointer-events: none;
  position: absolute;
  top: 50%;
  transform: translate(-50%, -50%);
  width: 100%;
}

.background { z-index: 0; }
.render { max-height: 93%; max-width: 93%; z-index: 1; }

.ovr,
.position,
.name {
  line-height: 1;
  position: absolute;
  text-shadow: 0 1px 2px rgba(0, 0, 0, 0.38);
  z-index: 2;
}

.ovr {
  color: var(--card-ovr-color);
  font-family: "FCOAllSans-Bold", sans-serif;
  font-size: 12.5cqi;
  left: 22%;
  top: 10%;
}

.position {
  color: var(--card-position-color);
  font-family: "FCOAllSans-Regular", sans-serif;
  font-size: 8.4cqi;
  left: 23%;
  top: 24%;
}

.name {
  bottom: 25.5%;
  color: var(--card-name-color);
  font-family: "FCOAllSans-Regular", sans-serif;
  font-size: 8.75cqi;
  left: 50%;
  overflow: hidden;
  text-align: center;
  text-overflow: ellipsis;
  transform: translateX(-50%);
  white-space: nowrap;
  width: 55%;
}

.icons {
  align-items: center;
  bottom: 16.1%;
  display: flex;
  gap: 5%;
  justify-content: center;
  left: 0;
  position: absolute;
  right: 0;
  z-index: 2;
}

.icons img {
  height: 8.33cqi;
  object-fit: contain;
  width: auto;
}

@supports not (font-size: 1cqi) {
  .ovr { font-size: 12.5%; }
  .position { font-size: 8.4%; }
  .name { font-size: 8.75%; }
}
</style>
